import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Building2, Zap, Code2, Database, Shield, ChevronLeft, ChevronRight } from 'lucide-react';

interface JourneyStep { id: string; icon: React.FC<{ className?: string; color?: string }>; title: string; narrative: string; before: string; after: string; highlight?: string; color: string; }

const steps: JourneyStep[] = [
  { id: 'client', icon: Building2, title: 'Urbanismo digital em SP', narrative: 'A SMUL é responsável pelo planejamento urbano e licenciamento de obras na maior cidade da América Latina. O sistema Aprova Digital digitaliza os processos de licenciamento.', before: 'Sistema Aprova Digital em ambiente on-premises com limitações', after: 'Arquitetura híbrida serverless + containers na AWS', color: '#1e40af' },
  { id: 'serverless', icon: Zap, title: 'Arquitetura serverless', narrative: 'API Gateway + Lambda + SQS/SNS para novos microserviços event-driven, integrando com sistemas municipais como SEI-SP e bases geoespaciais.', before: 'Integrações manuais com sistemas municipais', after: 'Microserviços serverless com API Gateway + Lambda + SQS/SNS', highlight: 'Event-driven para integrações municipais', color: '#7c3aed' },
  { id: 'apis', icon: Code2, title: '5 APIs middleware Python', narrative: 'SEI-SP, Taxas-SP, Integrações-SP, BDT-SP (geoespacial) e API Aprova Digital — todas em EC2 com Docker e supervisão Monit para restart automático.', before: 'APIs sem containerização e sem supervisão automática', after: '5 APIs em Docker com Monit para restart automático', color: '#0891b2' },
  { id: 'db', icon: Database, title: 'MongoDB com réplica e backup', narrative: 'MongoDB em EC2 com réplica configurada, backup automatizado para S3 e procedimentos de restore documentados e testados.', before: 'Banco de dados sem réplica e backup manual', after: 'MongoDB com réplica, backup S3 e restore documentado', color: '#059669' },
  { id: 'security', icon: Shield, title: 'CloudFront + WAF', narrative: 'Amazon CloudFront como CDN para entrega de conteúdo estático e AWS WAF para proteção contra ataques web. Route 53 para DNS gerenciado.', before: 'Sem CDN e sem proteção contra ataques web', after: 'CloudFront + WAF + Route 53 para segurança e performance', color: '#dc2626' },
];

export const SMULDemo: React.FC = () => {
  const [activeStep, setActiveStep] = useState(0);
  const step = steps[activeStep]; const Icon = step.icon;
  const progressPct = ((activeStep + 1) / steps.length) * 100; const isLast = activeStep === steps.length - 1;
  return (
    <div className="w-full max-w-4xl mx-auto my-8">
      <div className="relative rounded-2xl border border-slate-200 bg-white overflow-hidden shadow-lg">
        <motion.div className="absolute inset-0 pointer-events-none" animate={{ background: `radial-gradient(ellipse 60% 40% at 50% 20%, ${step.color}08 0%, transparent 70%)` }} transition={{ duration: 0.8 }} />
        <div className="relative p-5 md:p-8 space-y-6">
          <div className="flex items-center gap-1">{steps.map((s, i) => { const StepIcon = s.icon; const done = i < activeStep; const active = i === activeStep; return (<React.Fragment key={s.id}><motion.button onClick={() => setActiveStep(i)} className="relative shrink-0" whileHover={{ scale: 1.15 }} whileTap={{ scale: 0.9 }} aria-label={s.title}><motion.div className="w-9 h-9 md:w-10 md:h-10 rounded-full flex items-center justify-center border-2 transition-all duration-300" animate={{ borderColor: active ? s.color : done ? '#10b981' : '#e2e8f0', backgroundColor: active ? `${s.color}12` : done ? 'rgba(16,185,129,0.08)' : 'white' }}>{done ? <motion.span initial={{ scale: 0 }} animate={{ scale: 1 }} className="text-emerald-500 text-xs font-bold">✓</motion.span> : <StepIcon className="w-4 h-4" color={active ? s.color : '#94a3b8'} />}</motion.div></motion.button>{i < steps.length - 1 && <div className="flex-1 h-0.5 rounded-full overflow-hidden bg-slate-200"><motion.div className="h-full bg-emerald-500" animate={{ width: done ? '100%' : '0%' }} transition={{ duration: 0.4 }} /></div>}</React.Fragment>); })}</div>
          <AnimatePresence mode="wait"><motion.div key={step.id} initial={{ opacity: 0, y: 60 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -40 }} transition={{ duration: 0.4 }} className="space-y-5">
            <div className="flex items-start gap-4"><motion.div className="w-12 h-12 md:w-14 md:h-14 rounded-2xl flex items-center justify-center shrink-0 border" style={{ borderColor: `${step.color}25`, backgroundColor: `${step.color}10` }}><Icon className="w-6 h-6" color={step.color} /></motion.div><div className="min-w-0"><div className="text-[10px] uppercase tracking-wider font-medium mb-1" style={{ color: step.color }}>Etapa {activeStep + 1} de {steps.length}</div><h3 className="text-lg md:text-xl font-bold text-slate-800 mb-2">{step.title}</h3><p className="text-sm text-slate-500 leading-relaxed">{step.narrative}</p></div></div>
            {step.highlight && <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: 0.2 }} className="text-center py-3 rounded-xl border" style={{ borderColor: `${step.color}20`, background: `linear-gradient(135deg, ${step.color}06 0%, transparent 100%)` }}><span className="text-base md:text-lg font-bold" style={{ color: step.color }}>{step.highlight}</span></motion.div>}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3"><motion.div initial={{ opacity: 0, x: -15 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.1 }} className="p-4 rounded-xl border border-red-200 bg-red-50"><div className="text-[10px] uppercase tracking-wider font-bold text-red-500 mb-2">Antes</div><p className="text-sm text-red-700/70">{step.before}</p></motion.div><motion.div initial={{ opacity: 0, x: 15 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.3 }} className="p-4 rounded-xl border border-emerald-200 bg-emerald-50"><div className="text-[10px] uppercase tracking-wider font-bold text-emerald-600 mb-2">Depois</div><p className="text-sm text-emerald-700/70">{step.after}</p></motion.div></div>
          </motion.div></AnimatePresence>
          <div className="flex items-center justify-between"><motion.button onClick={() => setActiveStep(prev => Math.max(0, prev - 1))} disabled={activeStep === 0} className="flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs border border-slate-200 text-slate-500 hover:text-slate-700 disabled:opacity-30 disabled:cursor-not-allowed" whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}><ChevronLeft className="w-3.5 h-3.5" /> Anterior</motion.button><motion.button onClick={() => setActiveStep(prev => Math.min(steps.length - 1, prev + 1))} disabled={isLast} className="flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs border border-slate-200 text-slate-500 hover:text-slate-700 disabled:opacity-30 disabled:cursor-not-allowed" whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>Próxima <ChevronRight className="w-3.5 h-3.5" /></motion.button></div>
          <div className="h-1 bg-slate-100 rounded-full overflow-hidden"><motion.div className="h-full rounded-full" style={{ backgroundColor: step.color }} animate={{ width: `${progressPct}%` }} transition={{ type: 'spring', stiffness: 200, damping: 25 }} /></div>
          {isLast && <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="text-center py-4 rounded-xl bg-emerald-50 border border-emerald-200"><p className="text-sm text-emerald-700 font-medium">Sistema Aprova Digital operacional na AWS com arquitetura serverless e containers.</p></motion.div>}
        </div>
      </div>
    </div>
  );
};
